### ISSUE TITLE
can you provide  some simple  examples  with  codesandbox?

### ISSUE THREAD

**Issue by zxhycxq** [extractus/article-extractor#290]
I can't run it well. if have some base examples, so much the better。thanks.
![image](https://user-images.githubusercontent.com/11674203/188570033-f4ba6169-539a-4953-be6b-255c9fadc354.png)

**Comment by ndaidong** [comment]
@zxhycxq sorry, I'm not sure about the mechanism behind Codesandbox. I even cannot get the default app they created runs:

![Screenshot from 2022-09-06 17-09-34](https://user-images.githubusercontent.com/1809619/188609001-8b5c6242-b42a-4b80-9a5e-b7deef5c27da.png)

**Comment by ndaidong** [comment]
@zxhycxq yes, basically it was designed to work on Node.js server side only. Some contributors have added typescript support to get it runs on several TypeScript environment such as Deno, but I'm sure that it can't work at client side.
