### ISSUE TITLE
[bug] - Garbled when the some link is in Chinese

### ISSUE THREAD

**Issue by zxhycxq** [extractus/article-extractor#320]
when the url is like `http://media.people.com.cn/n1/2020/0617/c40606-31749210.html`,then the result was:

![image](https://user-images.githubusercontent.com/11674203/204138140-62e1c664-a7cd-47cb-936f-e942b45a9168.png)
![image](https://user-images.githubusercontent.com/11674203/204138572-2514479e-1b77-45c8-9e88-5a7cac5be485.png)

however, this link is in chinese too, it was right.

`https://juejin.cn/post/6931597891182002183`

![image](https://user-images.githubusercontent.com/11674203/204138423-9d78e708-cc25-4aae-9e9d-28b9c3b6a36e.png)

how to solve this problem？change the UNICODE? thanks you!

**Comment by SettingDust** [comment]
人民网使用的是 GBK，本库需要读取编码

The people.com use the gbk encoding `<meta http-equiv="content-type" content="text/html;charset=GB2312">`. We need read the content type of document @ndaidong

**Comment by ndaidong** [comment]
@zxhycxq yes it relates to the charset of that websit as  @SettingDust  pointed out. 

 @SettingDust then what we should do next? Does it require to convert the whole content to UTF8?

**Comment by SettingDust** [comment]
@ndaidong Yup, need lib like `iconv-lite` to convert the encoding. But we can't know if the html string is as same as the meta(input string maybe utf-8 but with other encoding in meta). So I think the encoding should specific from options or users should convert the input by themselves.

**Comment by zxhycxq** [comment]
We can provide an option for users to choose,if possible.

**Comment by SettingDust** [comment]
> We can provide an option for users to choose,if possible.

I prefer users convert the input by themselves

**Comment by ndaidong** [comment]
yes, as far as I can see this is just an exception. User should find a way to handle it by himself. 
In this case, the process could be: load HTML --> convert to UTF-8 --> pass converted UTF-8 string to article-parser

**Comment by SettingDust** [comment]
> I still encounter this problem after iconv to UTF-8. The extractor seems to fail silently with null output.
> 
> You can try reproducing this by dumping the HTML source from the browser and read it in nodejs.

You have to confirm the content you input is gbk.

**Comment by ndaidong** [comment]
Resolved with v8.0.8
