### ISSUE TITLE
Rewrite relative image URLs to absolute ones

### ISSUE THREAD

**Issue by ghost** [extractus/article-extractor#321]
Is it possible to add something like puppeteer to handle Youtube/Twitter contents that requires Javascript?

FYI: https://gist.github.com/MrOrz/fb48f27f0f21846d0df521728fda19ce

**Comment by SettingDust** [comment]
article-parser absolutify all `<a>` or `<img>`
https://github.com/ndaidong/article-parser/blob/main/src/utils/linker.js#L109-L128

article-parser will try to find out the best url. 
https://github.com/ndaidong/article-parser/blob/main/src/utils/linker.js#L16-L19

@ndaidong Why not the `extract(html, url)` be exported?

**Comment by ndaidong** [comment]
@nick008a if you can `extract(html)`, it will automatically find original URL from [meta tags](https://github.com/ndaidong/article-parser/blob/main/src/utils/extractMetaData.js#L29). 

As your issue, I see that it's not perfect and developer should be able to pass original URL into `extract` metho manually.

**Comment by ndaidong** [comment]
@SettingDust we just posted in the same time. Yes, that's problem we need to resolve!

**Comment by ndaidong** [comment]
@SettingDust I have some ideas:

1. Expose `extractFromHTML` as public method

2. At current `extract` method, do the checks.

```
if input is URL:
  extract with URL as normal
else:
  treat first argument as HTML, third parameter (`fetchOptions`) as orginal URL 
```

How do you think?

**Comment by SettingDust** [comment]
How about overloads
```ts
export function extract(input: { url: string }, options: ParserOptions)
export function extract(input: { html: string }, options: ParserOptions)
export function extract(input: { url?: string, html?: string }, options: ParserOptions)
// @deprecated: the old logical
export function extract(input: string, options: ParserOptions)
```

**Comment by ndaidong** [comment]
@SettingDust that's good idea, except of changing api, we may need to break to new major version.

**Comment by ndaidong** [comment]
@SettingDust if we start a new major version, I suggest to:

- Rewrite in TypeScript
- Use only one argument:

```js
export function extract(input: { 
  url: string, 
  html: string, 
  parserOptions: ParserOptions, 
  fetchOptions: FetchOptions
})
```

So it woud be more flexible for the updates in future.

**Comment by SettingDust** [comment]
How about
```ts
export function extract(options: { 
  url: string, 
  html: string, 
  parser: ParserOptions, 
  fetch: FetchOptions
})
```
And some maybe helpful https://github.com/SettingDust/article-extractor/tree/main/src

**Comment by ndaidong** [comment]
@SettingDust yes, I'm moving to Deno.

**Comment by SettingDust** [comment]
URL import is experiment in node. Maybe it will work both platform? Agree deno

**Comment by ndaidong** [comment]
@SettingDust still learning, I see many libs are being built for both platforms.

**Comment by ndaidong** [comment]
@SettingDust you are developing a completely new variant. Why we don't simple create an organization together, and move this lib to there? With more 700 stars, this lib should not belong to an individual developer. It should be `@organization/article-parser`.

**Comment by SettingDust** [comment]
It's fine

**Comment by ndaidong** [comment]
@SettingDust any idea about organization name?

**Comment by SettingDust** [comment]
> @SettingDust any idea about organization name?

`article-parser/article-parser`? lul

**Comment by ndaidong** [comment]
@SettingDust it should cover more tools, I would like to move all its sibling too there: feed-reader, oembed-parser. And few more extractor tools in future: meta extractor, images extractor, price extractor...

**Comment by SettingDust** [comment]
In my own lib. I make it accept custom extractor to extract different metas. And the images and price should extractable with custom extractor. So, maybe "meta-extractor/meta-extractor"?

**Comment by ndaidong** [comment]
@SettingDust how about something strange, meaningless, greek style like `extractorius` or `extractus`?
In this organization will contain the repos name as x-extractor, and people can install them as `@extractus/x-extractor`.

**Comment by ndaidong** [comment]
@SettingDust I've added you as owner, and testing transfer function.

**Comment by ndaidong** [comment]
@nick008a if page HTML does not contain url meta tags, you may need to add them manually (using DOM manipulation). 

It expects one of these lines:

```html
<meta property="og:url" content="https://orginal-url.com/category/article/slug">
<meta property="twitter:url" content="https://orginal-url.com/category/article/slug">
```

**Comment by ndaidong** [comment]
@nick008a of course, they must be placed between `<head></head>`. It's regular meta tag as you often see at the SEO standard websites.

![Screenshot from 2022-11-29 15-42-27](https://user-images.githubusercontent.com/1809619/204481305-f529cf49-b27c-4b40-9c74-b041fc55eb9e.png)
