### ISSUE TITLE
HTML tags in content response

### ISSUE THREAD

**Issue by iDevo** [extractus/article-extractor#328]
Hi there! 
First of all - thanks for creating this awesome project and the API on RapidAPI! 

My issue is, that I am still receiving HTML tags for some article pages in my content response. 

Example URL: [https://www.gamestar.de/artikel/apple-ar-vr-brille-2023,3388549.html](https://www.gamestar.de/artikel/apple-ar-vr-brille-2023,3388549.html)

Response: 
`content:"<div> <p> <span> <picture> <img src="https://images.cgames.de/images/gamestar/290/apple-view_6212445.jpg" /> </picture> </span> <span>Apples erstes Mixed-Reality-Headset wird bereits in naher Zukunft enthüllt. (Konzept-Design von Ian Zelbo)</span> </p> <p>Dass Apple an einer Mixed-Reality-Brille arbeitet, ist bereits seit vielen Jahren bekannt. Das neue Gadget mit dem vermeintlichen Namen <a href="https://www.gamestar.de/artikel/apple-vr-ar-headset,3383906.html" target="_blank">Reality Pro sollte ursprünglich schon 2022 enthüllt werden</a>.</p> <p>Ferner arbeitet der Hersteller weiter an seinem neuen Betriebssystem xrOS, um auch Anwendungen, die wir von dem iPhone, iPad und Co. kennen, auf die smarte Brille zu übertragen. <a href="https://www.bloomberg.com/news/newsletters/2023-01-08/when-will-apple-launch-the-reality-pro-mixed-reality-headset-apple-2023-devices-lcnfzkc7" target="_blank">Laut dem renommierten Apple-Experten Mark Gurman</a> folgt die Vorstellung der Brille nun endlich 2023, genauer gesagt bereits im Frühjahr dieses Jahres. Das letzte spannende und neue Produkt aus dem Hause Apple liegt bald neun Jahre zurück: die Series 1 der Apple Watch.</p> <h2 id="apples-mixed-reality-brille-bereits-vor-der-wwdc">Apples Mixed-Reality-Brille bereits vor der WWDC?</h2> <p>Das Reality Pro-Headset von Apple soll laut Mark Gurman bereits vor der Entwickler-Konferenz angekündigt werden. Ziel dieser Strategie sei es, auf der WWDC das neue Betriebssystem mit dem Namen xrOS präsentieren zu können.</p> <p>Sollte sich diese Prognose bewahrheiten, dürfen wir in diesem Jahr also auf eine waschechte Neuerung aus dem Hause Apple gespannt sein. Ursprünglich sollte die smarte Brille wohl bereits im letzten Jahr das Licht der Welt erblicken.</p> <a target="_blank" title="Neben den neuen iPhones hätte auch Apples Mixed-Reality-Brille ursprünglich eine große Rolle auf der WWDC 2022 spielen sollen." href="https://images.cgames.de/images/gamestar/226/apple-wwdc-und-ios-16_6176028.jpg"> <p> <span> <picture> <img src="https://images.cgames.de/images/gamestar/290/apple-wwdc-und-ios-16_6176028.jpg" /> </picture> <span> <span> <i></i> </span> </span> </span> <span>Neben den neuen iPhones hätte auch Apples Mixed-Reality-Brille ursprünglich eine große Rolle auf der WWDC 2022 spielen sollen.</span> </p> </a> <p><strong>Wann erfolgt der offizielle Release der Mixed-Reality-Brille?</strong> Nach der Enthüllung des Headsets und der Präsentation des Betriebssystems xrOS plant Apple angeblich die Auslieferung des Gadgets schon im Herbst 2023.</p> <p>Der Hersteller aus Cupertino hat »hochkarätige Entwickler« mit der Arbeit an dem neuartigen Headset und dessen Betriebssystem xrOS beauftragt, so Mark Gurman. Bis ihr allerdings ein solches Gerät von Apple im Alltag verwendet, dürfte noch einiges an Zeit verstreichen. Das erste Mixed-Reality-Headset des Herstellers soll sich primär an professionelle Anwender richten und damit ein Nischenprodukt werden.</p> <p>Nicht nur Apple verfolgt entsprechende Pläne für ein neues Erlebnis, das ihr euch auf die Nase setzen könnt. Der Hardware-Hersteller Lenovo kündigte bereits im September 2022 seine erste smarte Brille an, die im Gegensatz zu Apples kommenden Ableger auch für Konsumenten konzipiert ist. TCL präsentierte auf der CES einen ähnlichen Ansatz:</p> <ul> <li><a href="https://www.gamestar.de/artikel/display-smarte-brille,3383873.html" target="_blank">Aufs Smartphone schauen und die Hände frei haben: Lenovo enthüllt Display zum Aufsetzen</a></li> <li><a href="https://www.gamestar.de/artikel/tcl-ar-brille-rayneo-x2,3388477.html" target="_blank">Apps auf eurer Brille: Dieses Sci-Fi-Gadget soll schon bald euer Handy ablösen</a></li> </ul> <p><em>Was haltet ihr von derartigen Konzepten? Könnt ihr euch vorstellen, in ferner Zukunft mit einer smarten Brille den Alltag zu bestreiten? Was haltet ihr von der Vorstellung, dass ein solches Gadget ein Smartphone ablösen könnte? Schreibt uns eure Meinung gerne in die Kommentare!</em></p> </div>"`

Is there any way for me to avoid this? 

Thank you very much!

**Comment by iDevo** [comment]
Sorry this is more a question towards the usage of the RapidAPI. In the description is mentioned to use sanitize-html.

**Comment by ndaidong** [comment]
@iDevo no problem, thank you for your compliment. If you have any question or need more help, please ask me.
