### ISSUE TITLE
Not all HTML attributes are extracted

### ISSUE THREAD

**Issue by victory-sokolov** [extractus/article-extractor#329]
First of all, thank you for creating such an excellent library.

I have a question, is it possible to extract `class `and `data-attributes`?

The extracted output contains some `id `attributes, but not `class `attributes.
Is this something supported or will it be supported at some point?

**Comment by ndaidong** [comment]
@victory-sokolov thank you for your compliment. This lib uses [sanitize-html](https://www.npmjs.com/package/sanitize-html) to remove unwanted HTML tags & attributes. You can change default options to get what you need.

Please refer [this section in README](https://github.com/extractus/article-extractor#sanitize-htmls-options).

**Comment by victory-sokolov** [comment]
@ndaidong Thanks a lot for pointing to the docs.
I''ve tried to use `setSanitizeHtmlOptions`, although the output HTML doesn't have class attributes.

I've verified that the `getSanitizeHtmlOptions` contains new options

Do I miss something?

```js
const currentSanitizeOptions = getSanitizeHtmlOptions();

setSanitizeHtmlOptions({
    ...currentSanitizeOptions,
    allowedAttributes: {
        ...currentSanitizeOptions.allowedAttributes,
        code: ['class'],
        div: ['class']
    },
    allowedClasses: {
        code: ['language-*', 'lang-*']
    }
});
```

**Comment by ndaidong** [comment]
@victory-sokolov you've done right. I confirmed that it does not return as expected.  I'm investigating this case.

**Comment by ndaidong** [comment]
@victory-sokolov Done! Please try the latest version to see if it works for you.

**Comment by victory-sokolov** [comment]
@ndaidong 
Thanks a lot, it works now!
