### ISSUE TITLE
Obscure parsing error on cheezburger.com

### ISSUE THREAD

**Issue by kylealwyn** [extractus/article-extractor#331]
Hello!

Having an issue parsing https://cheezburger.com/19495941/33-purrfect-cat-memes-for-all-the-grumpy-cats-on-monday-morning-february-27-2023 (or really any article on that site) both locally and on https://extractor-demos.pages.dev/article-extractor. Receiving `Cannot read properties of null (reading 'length')`.

**Comment by ndaidong** [comment]
@kylealwyn thank you. I've checked and will fix that now.

**Comment by ndaidong** [comment]
@kylealwyn done. However that website's HTML structure is not convenient for extracting article. You may need to add [transformations](https://github.com/extractus/article-extractor#transformations) to improve your extraction result.

**Comment by kylealwyn** [comment]
Appreciate it @ndaidong! Was coming here to share one more site with same issue: https://themerkle.com/exploring-the-potential-of-collateral-network-colt-ethereum-eth-and-quant-qnt/

Will see if 7.2.10 is solve for both!

**Comment by kylealwyn** [comment]
Ope - looks like 7.2.10 isn't published yet. Will wait for that.

**Comment by ndaidong** [comment]
@kylealwyn yes, v7.2.10 has just been published. And it works for themerkle.com too :heavy_check_mark:
