### ISSUE TITLE
extractFromHtml() returns null

### ISSUE THREAD

**Issue by shipcommit** [extractus/article-extractor#335]
`extract()` works fine, and returns the expected output.

When extracting data with `extractFromHtml()`, I get `null`.

I have tried the following examples, and they all return `null`.

```
const res = await fetch(url)
const html = await res.text()

const article = await extractFromHtml(html)

console.log(article);
```

```
const response = await got(url);

const data = await extractFromHtml(response.body);

console.log(data);
```

**Comment by shipcommit** [comment]
I would assume this data would work as the input, but it doesn't: 
![Skjermbilde 2023-03-25 103309](https://user-images.githubusercontent.com/35367024/227709280-b31a040c-40df-4ddf-b782-9483a178cd2a.png)

**Comment by ndaidong** [comment]
@shipcommit thank you, I will check this case asap.

**Comment by ndaidong** [comment]
@shipcommit hello, I could not reproduce the error as what you faced. Native `fetch` and `got` both work for me.
 Please share more info about your use case:

- Platform (Node.js 18.5.0, Bun 0.5.2)
- Article Extractor version 
- Your script in detail, url to extract, etc

Thank you.

**Comment by houshuang** [comment]
I get the same with this URL https://en.wikipedia.org/wiki/Plato, but exactly the same setup with this URL worked flawlessly. https://www.aftenposten.no/norge/i/69V75W/terrorsiktede-soestre-fra-baerum-paagrepet-av-pst

Would be nice if it could return the reason why it returns null, to make it easier to diagnose.

**Comment by houshuang** [comment]
Never mind, I figured it out - it was due to some pre-processing I was doing. Would still be nice with better error messages.

**Comment by ndaidong** [comment]
@houshuang thank you for your info and suggestion.
