### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by Roosteridk** [extractus/article-extractor#345]
Currently the npm specifiers limit deployment options. It would be nice to have a full Deno release.

**Comment by ndaidong** [comment]
@Roosteridk thanks for suggestion. I will look at the docs there to see how to apply.

**Comment by ndaidong** [comment]
This library lacks support for TypeScript and advanced type definitions, which are essential features for Deno module or JSR. 
Therefore, I temporarily closed this issue until there is a better solution.
