### ISSUE TITLE
Preserve multiline spaces for code blocks

### ISSUE THREAD

**Issue by victory-sokolov** [extractus/article-extractor#347]
Hello, was wondering if it's possible to make `stripMultispaces` as a boolean flag for the `parserOptions` of the `extract`  method, so stripMultispaces could be an optional argument

In specific cases when I'm extracting HTML that has code blocks that need to have multi spaces preserved, in order to maintain formatted code blocks.

Maybe you have any other ideas on how this can be achieved?

Thanks!

**Comment by ndaidong** [comment]
@victory-sokolov thank you for your idea. Could you explain more detail and suggest some links to test? I consider that if that is a specific case, we can simply use transformation.

**Comment by victory-sokolov** [comment]
Not sure if it will be straightforward to implement it using custom transformation.

Here is an example of the extracted code block

<pre data-language="jsx"><code data-language="jsx"><span class="line"><span>import</span><span> { </span><span>useTheme</span><span> } </span><span>from</span><span> </span><span>'next-themes'</span><span>;</span></span> <span class="line"> </span> <span class="line"><span>const</span><span> </span><span>ThemeChanger</span><span> </span><span>=</span><span> () </span><span>=&gt;</span><span> {</span></span> <span class="line"><span> </span><span>const</span><span> { </span><span>theme</span><span>, </span><span>setTheme</span><span> } </span><span>=</span><span> </span><span>useTheme</span><span>();</span></span> <span class="line"> </span> <span class="line"><span> </span><span>return</span><span> (</span></span> <span class="line"><span> &lt;</span><span>div</span><span>&gt;</span></span> <span class="line"><span> The current theme is: </span><span>{</span><span>theme</span><span>}</span></span> <span class="line"><span> &lt;</span><span>button</span><span> </span><span>onClick</span><span>=</span><span>{</span><span>() </span><span>=&gt;</span><span> </span><span>setTheme</span><span>(</span><span>'light'</span><span>)</span><span>}</span><span>&gt;Light Mode&lt;/</span><span>button</span><span>&gt;</span></span> <span class="line"><span> &lt;</span><span>button</span><span> </span><span>onClick</span><span>=</span><span>{</span><span>() </span><span>=&gt;</span><span> </span><span>setTheme</span><span>(</span><span>'dark'</span><span>)</span><span>}</span><span>&gt;Dark Mode&lt;/</span><span>button</span><span>&gt;</span></span> <span class="line"><span> &lt;/</span><span>div</span><span>&gt;</span></span> <span class="line"><span> );</span></span> <span class="line"><span>};</span></span></code></pre>

and this is the original code copied from the dev console ([site](https://leerob.io/blog/tailwind))

<pre data-language="jsx" data-theme="default"><code data-language="jsx" data-theme="default"><span class="line"><span style="color: rgb(198, 120, 221);">import</span><span style="color: rgb(171, 178, 191);"> { </span><span style="color: rgb(224, 108, 117);">useTheme</span><span style="color: rgb(171, 178, 191);"> } </span><span style="color: rgb(198, 120, 221);">from</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(152, 195, 121);">'next-themes'</span><span style="color: rgb(171, 178, 191);">;</span></span>
<span class="line"> </span>
<span class="line"><span style="color: rgb(198, 120, 221);">const</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(97, 175, 239);">ThemeChanger</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(86, 182, 194);">=</span><span style="color: rgb(171, 178, 191);"> () </span><span style="color: rgb(198, 120, 221);">=&gt;</span><span style="color: rgb(171, 178, 191);"> {</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">  </span><span style="color: rgb(198, 120, 221);">const</span><span style="color: rgb(171, 178, 191);"> { </span><span style="color: rgb(229, 192, 123);">theme</span><span style="color: rgb(171, 178, 191);">, </span><span style="color: rgb(229, 192, 123);">setTheme</span><span style="color: rgb(171, 178, 191);"> } </span><span style="color: rgb(86, 182, 194);">=</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(97, 175, 239);">useTheme</span><span style="color: rgb(171, 178, 191);">();</span></span>
<span class="line"> </span>
<span class="line"><span style="color: rgb(171, 178, 191);">  </span><span style="color: rgb(198, 120, 221);">return</span><span style="color: rgb(171, 178, 191);"> (</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">    &lt;</span><span style="color: rgb(224, 108, 117);">div</span><span style="color: rgb(171, 178, 191);">&gt;</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">      The current theme is: </span><span style="color: rgb(198, 120, 221);">{</span><span style="color: rgb(224, 108, 117);">theme</span><span style="color: rgb(198, 120, 221);">}</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">      &lt;</span><span style="color: rgb(224, 108, 117);">button</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(209, 154, 102); font-style: italic;">onClick</span><span style="color: rgb(86, 182, 194);">=</span><span style="color: rgb(198, 120, 221);">{</span><span style="color: rgb(171, 178, 191);">() </span><span style="color: rgb(198, 120, 221);">=&gt;</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(97, 175, 239);">setTheme</span><span style="color: rgb(171, 178, 191);">(</span><span style="color: rgb(152, 195, 121);">'light'</span><span style="color: rgb(171, 178, 191);">)</span><span style="color: rgb(198, 120, 221);">}</span><span style="color: rgb(171, 178, 191);">&gt;Light Mode&lt;/</span><span style="color: rgb(224, 108, 117);">button</span><span style="color: rgb(171, 178, 191);">&gt;</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">      &lt;</span><span style="color: rgb(224, 108, 117);">button</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(209, 154, 102); font-style: italic;">onClick</span><span style="color: rgb(86, 182, 194);">=</span><span style="color: rgb(198, 120, 221);">{</span><span style="color: rgb(171, 178, 191);">() </span><span style="color: rgb(198, 120, 221);">=&gt;</span><span style="color: rgb(171, 178, 191);"> </span><span style="color: rgb(97, 175, 239);">setTheme</span><span style="color: rgb(171, 178, 191);">(</span><span style="color: rgb(152, 195, 121);">'dark'</span><span style="color: rgb(171, 178, 191);">)</span><span style="color: rgb(198, 120, 221);">}</span><span style="color: rgb(171, 178, 191);">&gt;Dark Mode&lt;/</span><span style="color: rgb(224, 108, 117);">button</span><span style="color: rgb(171, 178, 191);">&gt;</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">    &lt;/</span><span style="color: rgb(224, 108, 117);">div</span><span style="color: rgb(171, 178, 191);">&gt;</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">  );</span></span>
<span class="line"><span style="color: rgb(171, 178, 191);">};</span></span></code></pre>

In general code, blocks have 4 spaces for nested blocks, but when an article is being scrapped it has only one, I guess this is because of the `stripMultispaces`. Maybe you have other ideas how those spaces can be preserved

Thanks in advance.

**Comment by ndaidong** [comment]
@victory-sokolov yeah, you are right. It's because of `stripMultispaces`. Let me see how we can make it as a configurable option.

**Comment by victory-sokolov** [comment]
@ndaidong Awesome thanks a lot! Now code blocks are formatted properly.
Thanks once again!

**Comment by ndaidong** [comment]
@victory-sokolov nice to see it works for you.
