### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module >=7.3.0

### ISSUE THREAD

**Issue by castroCrea** [extractus/article-extractor#360]
When I update from `7.2.6` to `>=7.3.0` I got this error `Error [ERR_REQUIRE_ESM]: require() of ES Module` 
I use it in `electronjs` so node.
I found that you remove `commonJS` but all your node examples use commonJS

What is the solution here ?

**Comment by ndaidong** [comment]
@castroCrea  it seems your platform still needs CJS support, similar to the issue #359 and extractus/oembed-extractor#177

Please try the version [v7.3.1](https://github.com/extractus/article-extractor/releases/tag/v7.3.1) I've just released.

**Comment by castroCrea** [comment]
Thank it works perfectly 🦾 
I'll add to my Roadmap to pass to ESM
