### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module >=8.0.2

### ISSUE THREAD

**Issue by BertrandBev** [extractus/article-extractor#366]
#360 Was resolved with 7.3.1 but seems broken again in 8.0.2

**Comment by ndaidong** [comment]
@BertrandBev yes. since v8.0, we stopped generating commonjs version.

**Comment by habibredissi** [comment]
@ndaidong We experiencing the same error. Do you know how to fix it for a (NodeJs + TypeScript) project.

`tsconfig.json`
```
{
  "compilerOptions": {
    "baseUrl": "./",
    "target": "ES2018",
    "module": "commonjs",
    "jsx": "react-jsx",
    "outDir": "./dist",
    "strict": true,
    "noEmit": true,
    "lib": ["es2015"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  },
  "ts-node": {
    "require": ["tsconfig-paths/register"]
  }
}
```

`package.json`:
`"start": "ts-node -T src/server.ts | bunyan",`


THANKS!!

**Comment by ndaidong** [comment]
@habibredissi  It's the time to switch completely to ESM, which you can safely use everywhere, from Node, Deno, Bun platfrom to the browsers.
