### ISSUE TITLE
Node example works but deno don't on a specific site

### ISSUE THREAD

**Issue by mirsella** [extractus/article-extractor#368]
hello !

The default node example works, but the default deno return `"Request failed with error code 403"` on articles from this specific site.
test url `localhost:3100/?url=https://www.lavoixdunord.fr/1380867/article/2023-10-04/le-chef-republicain-kevin-mccarthy-destitue-une-premiere-dans-l-histoire-des`

thanks !

**Comment by ndaidong** [comment]
@mirsella confirmed. I've tested fetch in Deno and it returned status 200 and HTML content as normal. So we may have something incorrect in the parser.

**Comment by ndaidong** [comment]
@mirsella not sure about the error, but if I use package from esm.sh, it works. Maybe the problem with npm specifier only. 

Just updated the example code.
