### ISSUE TITLE
Feat: extract pagetype from og:type or ld+json

### ISSUE THREAD

**Issue by andremacola** [extractus/article-extractor#373]
Recently, we worked on some projects using Trafilatura, but due to the team's familiarity with JavaScript, we are migrating one of them to the Article Extractor but missed extracting the page type (og:type).

We implemented [this feature](https://github.com/adbar/trafilatura/pull/310) in Trafilatura, and if you agree, we can submit a pull request here as well.

I think it would be interesting to extract the type of page, although some sites do not use Open Graph tags.

- Extract from og:type
- If no og:type tag, try to extract from ld+json

**Comment by ndaidong** [comment]
@andremacola hey there, I'm glad to hear you're finding the library valuable for your project!

I think that the page type does not bring much meaning to the core function of this library (extracting article content), other than a little hint that is not always correct.

However, I'm open to considering your PR if it doesn't bloat the codebase (e.g adding unnecessary dependencies or complexity isn't ideal).

**Comment by ndaidong** [comment]
@andremacola your pr has been merged and released in v8.0.4, hope that it works for you as expected.

Thank you for your contribution.
