### ISSUE TITLE
Encountering errors while using library inside NodeJS + TS project

### ISSUE THREAD

**Issue by ivkoandrv** [extractus/article-extractor#376]
I've encountered following error: 

`require() of ES Module *project_path*/node/node_modules/@extractus/article-extractor/src/main.js from *controller_name* not supported.\nInstead change the require of main.js in *controller-name* to a dynamic import() which is available in all CommonJS modules.`

I've tried connecting this thing in various ways:

1. As in doc: `import {extract} from "@extractus/article-extractor"`
2. Dynamic import: const ArticleExtract = await import("@extractus/article-extractor")

But, when I try it on the same, but the JS project - it works (I've use 1st method)

Node: 20

TS Config:
<img width="517" alt="image" src="https://github.com/extractus/article-extractor/assets/110159355/2022948c-1d0c-452f-a098-97b5eb36b391">

Help me, please, it's quite important

**Comment by ndaidong** [comment]
@ivkoandrv there is [an example](https://github.com/extractus/article-extractor/tree/main/examples/tsnode-article-parser) that works with Node.js / Typescript. I found that the most difference is `module` in TS config file. Could you try to change from "commonjs" to "es6"?

**Comment by ivkoandrv** [comment]
@ndaidong Yep, I've tried it. Maybe it's stuck with tsconfig at all. 

<img width="1196" alt="image" src="https://github.com/extractus/article-extractor/assets/110159355/4709b33b-41b1-43e7-93d2-2fb7ea49a431">

Thank's you

**Comment by ndaidong** [comment]
@ivkoandrv please try to run the example in your own environment to see if it works as expected. Then replace your project tsconfig file with the example config to verify if it's really the cause.

**Comment by ivkoandrv** [comment]
@ndaidong Yeah, example works perfect. I'll change my configuration
