### ISSUE TITLE
Expected ',' or '}' after property value in JSON at position 543 (line 23 column 7)

### ISSUE THREAD

**Issue by mirsella** [extractus/article-extractor#378]
hello !

`curl http://localhost:3100/?url=https://www.lonelyplanet.fr/article/croatie-croisiere-entre-dubrovnik-mljet-et-korcula`
```
{"error":1,"message":"Expected ',' or '}' after property value in JSON at position 543 (line 23 column 7)","data":null,"meta":{"service":"article-parser","lang":"javascript","server":"express","platform":"node"}}
```
The same happen with deno.

thanks !

**Comment by mirsella** [comment]
same if using `extractFromHtml` on the body

**Comment by ndaidong** [comment]
@mirsella thank you for your notice. I've checked, the issue relates to [extractLdSchema.js](https://github.com/extractus/article-extractor/blob/main/src/utils/extractLdSchema.js#L46). 

@andremacola this comes from #374, could you help to fix?

**Comment by andremacola** [comment]
I'll send a fix as soon as I can this week. I took a quick look on my phone and apparently the issue is with the website's own jsonLD. It's poorly formatted, missing a comma in one of the items.

I think we'll need to put in a validator or, to simplify, a try\catch.

**Comment by ndaidong** [comment]
@andremacola thank you, if so I will add a simple try/catch now, please improve it when you are available.
