### ISSUE TITLE
@extractus/article-extractor 8.0.6 isn't compatible with Google Cloud Functions

### ISSUE THREAD

**Issue by XinwenCheng** [extractus/article-extractor#383]
`"@extractus/article-extractor": "8.0.6",`

I integrated the latest version of `@extractus/article-extractor` into my Node.js project which is deployed on Google Cloud Functions. There always be an error that says:

> require() of ES Module /workspace/node_modules/@extractus/article-extractor/src/main.js from /workspace/managers/news.manager.js not supported. Instead change the require of main.js in /workspace/managers/news.manager.js to a dynamic import() which is available in all CommonJS modules.

I've already changed the regular importation to the dynamic one, but this error still occurs, no clue how to fix this. Any suggestion would be very helpful, thanks in advance!

By the way, @extractus/feed-extractor works well in this project, and it does not need to be imported dynamically.

![image](https://github.com/extractus/article-extractor/assets/795334/17b2ea54-cdc3-4079-8108-8770aaa23bc9)

And the following is the source code of `/node_modules/@extractus/article-extractor/src/main.js`, not sure which is the `require()` that error message mentioned.

![main js](https://github.com/extractus/article-extractor/assets/795334/f66ca6f3-4128-4b71-8e16-29b800bbdd97)

**Comment by XinwenCheng** [comment]
I compared both `package.json` files of `@extractus/article-extractor` and `@extractus/feed-extractor`, there's no essential difference here, and both of their `type` configs are `module`.

**Comment by ndaidong** [comment]
@XinwenCheng It seems your codebase might be using CommonJS style, or perhaps it's compiled to that format.
The reason why feed-extractor works while artcile-extractor doens't is some contributor has [added CJS support](https://github.com/extractus/feed-extractor/blob/main/package.json#L17) to feed-extractor.

**Comment by XinwenCheng** [comment]
Thank you @ndaidong for explaining this. I created a pull request https://github.com/extractus/article-extractor/pull/384 , hope it's correct.

**Comment by ndaidong** [comment]
@XinwenCheng thank you for your contribution, but I don't think building CJS version is the right approach at this time. Maybe you should look at how your code is being built. It may be in some config file like in [the issue 336](https://github.com/extractus/article-extractor/issues/366).

ESM has become the official standard, CJS has ended its mission. This library used to have a CJS version but was later removed from version [v7.3.0](https://github.com/extractus/article-extractor/releases/tag/v7.3.0), however it was restored in version v7.3.1 a short time later. You can use [v7.3.1](https://github.com/extractus/article-extractor/releases/tag/v7.3.1) temporarily.

I also ran this library natively on Google Cloud Functions and didn't have any problems.

**Comment by XinwenCheng** [comment]
Hi @ndaidong , thank you so much! V7.3.1 works for me!
