### ISSUE TITLE
img tag with "data" protocol was removed when doing purify

### ISSUE THREAD

**Issue by djyde** [extractus/article-extractor#388]
Here is a reproduce branch https://github.com/djyde/article-extractor/tree/purify-bad-case

https://github.com/djyde/article-extractor/commit/a84abe932b74dd9124355578b8854f06b52e01aa

In this case, when I use `extractFromHTML`, if my HTML has `img` tag with `data`(e.g.`data:image/webp`), the img will be removed.

After reading the source code, I found it was removed when `purify()`:

```ts
export const purify = (html) => {
  return sanitize(html, {
    allowedTags: false,
    allowedAttributes: false,
    allowVulnerableTags: true,
  })
}
```

if I pass `allowedSchemes: sanitize.defaults.allowedSchemes.concat(['data'])`, the img will not be removed:

```ts
export const purify = (html) => {
  return sanitize(html, {
    allowedTags: false,
    allowedAttributes: false,
    allowVulnerableTags: true,
    allowedSchemes: sanitize.defaults.allowedSchemes.concat(['data']),
  })
}
```

But in current version, I have no way to pass sanitize options for the `purify` function.

**Comment by ndaidong** [comment]
@djyde thank you for your feedback. Let's me see how this can be modified. However this lib has some problems with `sanitize-html`, I have no way to make it runs with the latest default config yet.

**Comment by ndaidong** [comment]
@djyde since v8.0.9, it no longer use purified html content for extraction engine. So your problem should be resolved.

**Comment by djyde** [comment]
I sync the latest main branch and run the test, it's still failed: https://github.com/djyde/article-extractor/tree/purify-bad-case
