### ISSUE TITLE
extractFromHtml just returns `null`.

### ISSUE THREAD

**Issue by bryantwilliam** [extractus/article-extractor#395]
This works:
```javascript
const { extract } = await import('@extractus/article-extractor');
return await extract("https://www.npmjs.com/package/@extractus/article-extractor#parseroptions-optional");
```

This returns `null`:
```javascript
const { extractFromHtml } = await import('@extractus/article-extractor');
return await extractFromHtml("<html><body><p>hi</p></body></html>", "https://www.npmjs.com/package/@extractus/article-extractor#parseroptions-optional");
```

This also returns `null`:
```javascript
const { extractFromHtml } = await import('@extractus/article-extractor');
return  await extractFromHtml("<html><body><p>hi</p></body></html>");
```

Using node.js for firebase cloud functions.

**Comment by ndaidong** [comment]
@bryantwilliam the html in your code is example or actual input? It should be full HTML content of that web page.

**Comment by bryantwilliam** [comment]
I tried with a full HTML page and it worked.

**Comment by bryantwilliam** [comment]
I tried with a full HTML page and it worked.

**Comment by spsaucier** [comment]
I'm getting `null` too, using `window.document.body.outerHTML` (in the browser) on this page for an example: https://news.yahoo.com/news/flipped-off-trooper-got-charged-152906016.html. I haven't been able to get it to give me any content, while https://extractor-demos.pages.dev/article-extractor works great.

**Comment by spsaucier** [comment]
`extract` after `GET`ting that page works in the browser, but I still am unable to get `extractFromHtml` to return an object rather than `null`.

**Comment by bryantwilliam** [comment]
Needs to include the <head> in the html, not just <body>

**Comment by spsaucier** [comment]
That's working, thanks!
