### ISSUE TITLE
Site with elementor theme/plugin doesn't work

### ISSUE THREAD

**Issue by andremacola** [extractus/article-extractor#397]
Maybe the elementor  wp plugin/theme is the cause?

https://expressopb.net/2024/05/19/alimentacao-basica-e-quase-5-vezes-mais-cara-do-que-consumo-exagerado-de-bebidas-alcoolicas-diz-estudo-da-ufpb/

OBS: Trafilatura can pull but it uses another extract algorithm.

I'll try to look into it.

**Comment by ndaidong** [comment]
@andremacola I could not access this website. Also tested with Pingdom. It seems to be restricted to US users only?

![Screenshot from 2024-09-11 23-10-16](https://github.com/user-attachments/assets/05a8405f-7888-49fc-8a85-e84f58c514d8)

**Comment by andremacola** [comment]
I think Brazil only. I'll host the html in a temp link later.

**Comment by andremacola** [comment]
The problem is with Readability, which cannot identify the content due to the organization of Elementor. I solved it by adding a reference class for the articles using `pre` in the transformationOption for the specific site.
