### ISSUE TITLE
update the response result format

### ISSUE THREAD

**Issue by mirsella** [extractus/article-extractor#407]
this is no longer correct:
```ts
{
  url: String,
  title: String,
  description: String,
  image: String,
  author: String,
  favicon: String,
  content: String,
  published: Date String,
  type: String, // page type
  source: String, // original publisher
  links: Array, // list of alternative links
  ttr: Number, // time to read in second, 0 = unknown
}
```
latest broke my application as the result for example author, is now something like
```ts
  "author": {
    "@type": "Person",
    "name": "Chris Baraniuk"
  },
  ```
and published if not found, is now null instead of a empty string

**Comment by ndaidong** [comment]
@mirsella yes, the latest update relates to `published`. It should be empty string instead of null when no date value detected.
However it has nothing to do with `author` property. Except of the target page contains jsonld data.
Could you share your article url?

**Comment by mirsella** [comment]
hey !
for example this url https://www.bbcearth.com/news/the-winged-giant-that-was-bigger-than-t-rex

return as author:
```json
  "author": {
    "@type": "Person",
    "name": "Chris Baraniuk"
  },
  ```

and as published, instead of the usual empty string when not finding a date, return null, on the latest version of this library, tested with the bun and deno version:
```json
  "published": null,
  ```

**Comment by mirsella** [comment]
on your demo site https://extractor-demos.pages.dev/article-extractor this is still a empty string, so i guess its on a recent version that wasn't yet put on your site

**Comment by ndaidong** [comment]
@mirsella yes, we should avoid the inconsistency. I will release a new version.

**Comment by mirsella** [comment]
personally i've adapted my code to match the api return so i dont "care" anymore, but updating the schema for new user would be nice, and avoid breaking change like this on a minor version bump (both author and published are breaking change)

thanks, have a good day

**Comment by ndaidong** [comment]
@mirsella your are right, I didn't carefully check the recent pr!

**Comment by mirsella** [comment]
just missing the update response format in the readme, i would have done a PR but i don't know enough the project to says what exactly can be assigned to the field author like the @type

**Comment by ndaidong** [comment]
@mirsella I try to keep the output structure as before. `published` and `author` must be string. So there is no change.

**Comment by mirsella** [comment]
oh ok author is also getting it's previous comportement, nice
